In [3]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

In [5]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


# Dimensions(ndim)
#### Dimension = number of levels in the array (1D = line, 2D = table, 3D = cube).

In [6]:
a=np.array(5)
print(f'Dimensions: {a.ndim}')
print(a)
b=np.array([1,2,3]) 
print(f'Dimensions: {b.ndim}')
print(b)
c=np.array([[1,2,3],[4,5,6]])
print(f'Dimensions: {c.ndim}')
print(c)
d=np.array([[[1,2,3],[4,5,6]]])
print(f'Dimensions: {d.ndim}')
print(d)
e=np.array([[[[]]]])
print(f'Dimensions: {e.ndim}')
f=np.array([[[[[[],[]]]]]])
print(f'Dimensions: {f.ndim}')

Dimensions: 0
5
Dimensions: 1
[1 2 3]
Dimensions: 2
[[1 2 3]
 [4 5 6]]
Dimensions: 3
[[[1 2 3]
  [4 5 6]]]
Dimensions: 4
Dimensions: 6


In [7]:

a = np.array([
    [[1, 2, 3],
     [4, 5, 6],[7,8,9]],
    
    [[7, 8, 9],
     [10, 11, 12],[13,14,15]]
])

print(a.ndim)   

3


In [8]:
import numpy as np

a = np.array([[1, 2], [3]])


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

# ndmin

#### ndmin is an argument used in np.array() to set the minimum number of dimensions an array should have.

In [9]:
a=np.array([1,2,3],ndmin=5)
print(a)
print(a.ndim)

[[[[[1 2 3]]]]]
5


In [10]:
b=np.array([[[1,2,3],[4,5,6]]],ndmin=5)
print(b)
print(b.ndim)

[[[[[1 2 3]
    [4 5 6]]]]]
5


In [11]:
c=np.array([[1,2,3]],ndmin=1)
print(c)
# What happens if you set ndmin smaller than the data’s current dimension?
# ➡️ Answer: Nothing changes. NumPy ignores it since the data already has higher dimensions.

[[1 2 3]]


In [12]:
d=np.array(5,ndmin=6)
print(d)

[[[[[[5]]]]]]


# NumPy Array Indexing

In [13]:
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[-1])
print(arr[-3])
print(arr[3]+arr[2])

1
4
2
7


In [14]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0,-1])
print(arr[1,-1])
print(arr[1,0])
print(arr[0,0])

5
10
6
1


In [15]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,-1])
print(arr[1,1,1])
print(arr[0,0,2])
print(arr[1,0,1])

6
11
3
8


# Slicing

In [16]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[0:5:2])

[1 3 5]


In [17]:
arr=np.array([[1,2,3,4],[6,7,8,9]])
print(arr[1,1:])
print(arr[0,-4:-1:2])

[7 8 9]
[1 3]


In [18]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,2])
print(arr[0:2,0:])
print(arr[0:2,2:4])
print(arr[0:2,0::2])

[3 8]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[3 4]
 [8 9]]
[[ 1  3  5]
 [ 6  8 10]]


# DataTypes

# dtype
#### In NumPy, dtype stands for “data type”. It tells NumPy what kind of data is stored in an array

In [19]:
#integer 
arr_i=np.array([1,2,3,4,5],dtype='i')
print(arr_i)
print(arr_i.dtype)
arr_i64 = np.array([1, 2, 3, 4, 5], dtype='int64')
print(arr_i64.dtype)

# Boolean
arr_b = np.array([True, False, True], dtype='b')
print("Boolean (b):", arr_b)
print(arr_b.dtype) 

# Unsigned Integer
arr_u = np.array([1, 2, 3], dtype='u8')
print("Unsigned Integer (u):", arr_u)
print(arr_u.dtype)

# Float
arr_f = np.array([1.5, 2.5, 3.5], dtype='f')
print("Float (f):", arr_f)
print(arr_f.dtype)

# Complex Float
arr_c = np.array([1+2j, 3+4j], dtype='c8')
print("Complex Float (c):", arr_c)
print(arr_c.dtype)

# Timedelta
arr_m = np.array(['1', '2', '3'], dtype='m')  # timedelta64
print("Timedelta (m):", arr_m)
print(arr_m.dtype)

# Datetime
arr_M = np.array(['2025-10-08', '2025-10-09'], dtype='M')  # datetime64
print("Datetime (M):", arr_M)
print(arr_M.dtype)

# Object
arr_O = np.array([{'a':1}, [1,2,3], "hello"], dtype='O')
print("Object (O):", arr_O)
print(arr_O.dtype)

# Byte String
arr_S = np.array([b'abc', b'def'], dtype='S')
print("Byte String (S):", arr_S)
print(arr_S.dtype)

# Unicode String
arr_U = np.array(['abc', 'def'], dtype='U')
print("Unicode String (U):", arr_U)
print(arr_U.dtype)

# Void (raw memory / fixed-size block)
arr_V = np.zeros(3, dtype='V10')  # 3 blocks of 10 bytes each
print("Void (V):", arr_V)
print(arr_V.dtype)

[1 2 3 4 5]
int32
int64
Boolean (b): [1 0 1]
int8
Unsigned Integer (u): [1 2 3]
uint64
Float (f): [1.5 2.5 3.5]
float32
Complex Float (c): [1.+2.j 3.+4.j]
complex64
Timedelta (m): [1 2 3]
timedelta64
Datetime (M): ['2025-10-08' '2025-10-09']
datetime64[D]
Object (O): [{'a': 1} list([1, 2, 3]) 'hello']
object
Byte String (S): [b'abc' b'def']
|S3
Unicode String (U): ['abc' 'def']
<U3
Void (V): [b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00']
|V10


# Overflow Errors

In [9]:
print(bin(50))
print(len(bin(50)[2:]))
# required 6 bits to store 50 so we can use 8 bits

0b110010
6


In [11]:
print(bin(50000000))
print(len(bin(50000000)[2:]))
# required 26 bits to store 50000000 so we can use 32 bits

0b10111110101111000010000000
26


In [12]:
print(bin(5000000000))
print(len(bin(50000000000)[2:]))
# required 36 bits to store 5000000000 so we can use 64 bits

0b100101010000001011111001000000000
36


In [14]:
# can we store 5000000 in in in8
arr=np.array(5000000,dtype=np.int8)

C:\Users\masir\AppData\Local\Temp\ipykernel_15776\2798480883.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 5000000 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr=np.array(5000000,dtype=np.int8)


In [15]:
arr

array(64, dtype=int8)

In [ ]:
# | Type  | Bits |                     Signed Range                         |        Unsigned Range           |
# | int8  |   8  |                       −128 to +127                       |             0 to 255            |
# | int16 |  16  |                    −32,768 to +32,767                    |           0 to 65,535           |
# | int32 |  32  |             −2,147,483,648 to +2,147,483,647             |        0 to 4,294,967,295       |
# | int64 |  64  | −9,223,372,036,854,775,808 to +9,223,372,036,854,775,807 | 0 to 18,446,744,073,709,551,615 |


In [ ]:
# For signed integers, NumPy uses two’s complement arithmetic.
# So:
# Stored Value=(Original Value mod 256)
# Then, if the result ≥ 128, it’s interpreted as a negative number:
# Final Value=Stored Value−256

In [ ]:
# 5000000 % 256 = 64

In [16]:
arr = np.array(5000129, dtype=np.int8)
print(arr)


-63


C:\Users\masir\AppData\Local\Temp\ipykernel_15776\1540619251.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 5000129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr = np.array(5000129, dtype=np.int8)


In [ ]:
# 5000129 % 256 = 193
# Now, since 193 ≥ 128 → use the second formula:
# final_value=193−256=−63

In [ ]:
# unsigned integers
# Unsigned integers don’t have negative values, so there’s no two’s complement adjustment.
# They use modular arithmetic only:
# Final Value=Original Value mod 256
# That’s it — no subtraction, no negatives.

In [18]:
arr = np.array(2000000, dtype=np.uint8)
print(arr)
# 2000000%256=128

128


C:\Users\masir\AppData\Local\Temp\ipykernel_15776\3088997141.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 2000000 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr = np.array(2000000, dtype=np.uint8)


In [19]:
arr = np.array(-300, dtype=np.uint8)
print(arr)
# When using modulo with a negative number, we find the positive equivalent that fits in 0–255 range:
# −300 mod 256=256−(300mod256)
# ⇒−300 mod 256=256−44=212

212


C:\Users\masir\AppData\Local\Temp\ipykernel_15776\3412703530.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -300 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr = np.array(-300, dtype=np.uint8)


# MEMORY
#### numpy is more memory efficient than lists

In [25]:
import sys
a=[1,2,3,4,5]
c=np.array(a)
print(sys.getsizeof(a))
print(c.nbytes)

104
40


# # Speed
# Why NumPy is faster than Python lists:

#### Implemented in C

#### NumPy arrays are implemented in C, which is a compiled, low-level language.

#### Operations on arrays are performed at C-speed, not Python-speed.

#### Contiguous memory storage

#### NumPy arrays store elements continuously in memory, unlike Python lists which store pointers to objects.

#### This allows vectorized operations and fast access using CPU cache efficiently.

#### Vectorized operations

#### NumPy can perform operations on the whole array at once instead of looping in Python.




In [28]:
a=[1,2,3,4]*1000
import time
start=time.time()
[i**2 for i in a]
end=time.time()
print(f'total time consumed is {end-start:.4f} seconds')


total time consumed is 0.0003 seconds


In [29]:
b=np.array(a)
start=time.time()
b**2
end=time.time()
print(f'total time consumed is {end-start:.4f} seconds')

total time consumed is 0.0002 seconds


# Shape
#### The shape of an array is the number of elements in each dimension.

In [32]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [35]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [36]:
arr1=np.array([[[[[[]]]]]])
print(arr1.shape)


(1, 1, 1, 1, 1, 0)


In [3]:
import numpy as np
arr2=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr2.shape

(2, 2, 3)

# Differnt Types of an Array

# 1.np.array()

In [37]:
arr=np.array([1,2,3,'4.5','a'])
print(arr)
print(arr.dtype) 

['1' '2' '3' '4.5' 'a']
<U21


In [39]:
arr1=np.array([1,2,3,4.5])
print(arr1)
print(arr1.dtype)

[1.  2.  3.  4.5]
float64


In [42]:
arr2=np.array([1,2,3,4],dtype=float,ndmin=4)
print(arr2)
print(arr2.dtype)

[[[[1. 2. 3. 4.]]]]
float64


# 2.arange()
#### creates array with evenly spaced values

In [48]:
?np.arange

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

In [46]:
arr=np.arange(0,5)
print(arr)

[0 1 2 3 4]


In [50]:
arr_f=np.arange(0,1,0.2,dtype=float)
print(arr_f)

[0.  0.2 0.4 0.6 0.8]


In [51]:
arr1=np.arange(5,0,-1)
print(arr1)

[5 4 3 2 1]


In [52]:
arr2=np.arange(12,dtype=float).reshape(3,4)
print(arr2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


# 3.linspace()


#### specific no of points


In [54]:
arr=np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [56]:
arr=np.linspace(0,10,5,dtype=int)
print(arr)

# np.linspace() first generates evenly spaced float values:
# [0.0, 2.5, 5.0, 7.5, 10.0]
# Then, when you use dtype=int, NumPy converts those floats into integers (by truncating or rounding down).

[ 0  2  5  7 10]


In [57]:
arr1=np.linspace(0,10,5,endpoint=False)
print(arr1)
# Normally, if endpoint=True → step size = (stop - start) / (num - 1)
# When endpoint=False → step size = (stop - start) / num

[0. 2. 4. 6. 8.]


In [59]:
arr,restep=np.linspace(0,10,5,endpoint=False,retstep=True)
print(arr)
print(restep)

[0. 2. 4. 6. 8.]
2.0


In [60]:
arr=np.linspace(1,12,12,dtype=float).reshape(3,4)
print(arr)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


# 4.Zeros()

In [61]:
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [62]:
arr=np.zeros((2,3),dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]]


In [63]:
arr=np.zeros((2,2,2))
print(arr)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [64]:
arr=np.zeros(3,dtype=complex)
print(arr)

[0.+0.j 0.+0.j 0.+0.j]


# 5.ones()

In [65]:
arr=np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [67]:
arr=np.ones((3,3),dtype=int)
print(arr,arr.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]] int64


In [68]:
arr=np.ones((3,3,3))
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [69]:
arr=np.ones((3,3),dtype=complex)
print(arr)


[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


# 6.full()

In [72]:
arr=np.full((2,2),7)
print(arr)

[[7 7]
 [7 7]]


In [73]:
arr=np.full((2,2),7,dtype=complex)
print(arr)

[[7.+0.j 7.+0.j]
 [7.+0.j 7.+0.j]]


In [74]:
arr=np.full((2,2),'hi')
print(arr)

[['hi' 'hi']
 ['hi' 'hi']]


In [77]:
arr=np.full((2,2),3.14)
print(arr)

[[3.14 3.14]
 [3.14 3.14]]


# 7.eye()

In [5]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
arr=np.eye(3,k=1)
print(arr)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [8]:
arr=np.eye(2,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]]


In [11]:
arr=np.eye(2,3,k=1,dtype=int)
print(arr)

[[0 1 0]
 [0 0 1]]


# 8.random.uniform()

In [5]:
# np.random.rand-->creating datapoints from a random distribution between 0 and 1
# np.random.randn-->creating normalized datapoints from a random distribution between 0 and 1
# np.random.uniform-->creating datapoints from a uniform distribution


In [4]:
arr=np.random.uniform(0,1,5)
print(arr)

[0.44587982 0.444469   0.6601826  0.36975979 0.36521728]


In [13]:
arr1=np.random.uniform(-5,5,(2,3))
print(arr1)

[[ 2.51060818  1.05306135 -4.91086942]
 [ 1.86460549  1.12149598 -2.84463232]]


In [14]:
arr2=np.random.uniform(0,10)
print(arr2)

7.849971143794374


In [15]:
arr3=np.random.uniform(1,100,(4,5))
print(arr3)

[[69.8111663  16.67269414 85.96565165 64.06493344 20.5895193 ]
 [21.20754395  2.52469263 67.43594525 99.73143226  6.18853495]
 [45.77279396 28.75553628 31.37311035 36.81141324 94.32576409]
 [81.665593   50.6231046  71.99204311 13.91890379 55.08923059]]


# 9.random.randint()

In [16]:
arr=np.random.randint(1,10,5)
print(arr)

[9 3 6 7 1]


In [21]:
arr1=np.random.randint(-5,5,(2,3))
print(arr1)

[[ 0 -3  4]
 [ 2 -4 -1]]


In [22]:
arr=np.random.randint(0,100)
print(arr)

79


In [25]:
a=np.random.randint(1,1000,(4,5))
print(a)

[[254 346 432 202 962]
 [ 81 219  36 207 702]
 [627 997  28 890 418]
 [783 925 144 991 965]]


# 10.random.randn()

In [30]:
?np.random.randn

Signature: np.random.randn(*args)
Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned 

In [26]:
arr=np.random.randn(5)
print(arr)

[-0.90055934 -0.88962796 -2.49466954 -2.38133529  0.66168782]


In [34]:
arr1 = np.random.randn(2, 3)
print(arr1)



[[ 1.47793767  0.48980172 -0.01715385]
 [-1.06408195 -2.12369148 -0.80546175]]


In [35]:
arr2 = np.random.randn(2, 2, 2)
print(arr2)


[[[ 0.23132273 -1.18403038]
  [ 0.69186225  1.24333294]]

 [[ 1.34117316 -0.12611424]
  [-0.41066484 -1.43670582]]]


In [36]:
arr3 = 5 + 2 * np.random.randn(5)
print(arr3)


[5.78475245 7.56747638 3.69975377 6.1110085  3.03762812]


# 11.random.fromfunction()

In [37]:
arr=np.fromfunction(lambda i,j:i+j,(3,3))
print(arr)

# Explanation (Step-by-Step)
# The shape = (3, 3) → means we want a 3×3 matrix.
# NumPy internally creates index arrays:
# i = [[0, 0, 0],
#      [1, 1, 1],
#      [2, 2, 2]]
# j = [[0, 1, 2],
#      [0, 1, 2],
#      [0, 1, 2]]
# The function is lambda i, j: i + j
# → So it adds i and j element-wise.
# [[0+0, 0+1, 0+2],
#  [1+0, 1+1, 1+2],
#  [2+0, 2+1, 2+2]]
# That gives:
# [[0, 1, 2],
#  [1, 2, 3],
#  [2, 3, 4]]

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


In [38]:
arr1 = np.fromfunction(lambda i, j: i**2 + j**2, (3, 3), dtype=int)
print(arr1)
# [[0^2+0^2, 0^2+1^2, 0^2+2^2],
#  [1^2+0^2, 1^2+1^2, 1^2+2^2],
#  [2^2+0^2, 2^2+1^2, 2^2+2^2]]
# = [[0, 1, 4],
#    [1, 2, 5],
#    [4, 5, 8]]

[[0 1 4]
 [1 2 5]
 [4 5 8]]


In [39]:
arr2 = np.fromfunction(lambda i, j: i * j, (2, 4))
print(arr2)
# i indices:       j indices:       i*j (result):
# [[0 0 0 0]       [[0 1 2 3]       [[0 0 0 0]
#  [1 1 1 1]]      [0 1 2 3]]      [0 1 2 3]]


[[0. 0. 0. 0.]
 [0. 1. 2. 3.]]


In [40]:
arr3 = np.fromfunction(lambda i, j, k: i + j + k, (2, 2, 2))
print(arr3)
# i=[[[0 0]
#   [1 1]] 
#  [[0 0]
#   [1 1]]]

# j=[[[0 1]
#   [0 1]]
#  [[0 1]
#   [0 1]]]

# k=[[[0 0]
#   [0 0]]
#  [[1 1]
#   [1 1]]]

# Layer 0 (k=0):
# [[i+j+k]] = [[0+0+0, 0+1+0],
#              [1+0+0, 1+1+0]]
#            = [[0, 1],
#               [1, 2]]
# Layer 1 (k=1):

# [[i+j+k]] = [[0+0+1, 0+1+1],
#              [1+0+1, 1+1+1]]
#            = [[1, 2],
#               [2, 3]]

[[[0. 1.]
  [1. 2.]]

 [[1. 2.]
  [2. 3.]]]


# 12.empty()

In [41]:
arr=np.empty(5)
print(arr)

[5.78475245 7.56747638 3.69975377 6.1110085  3.03762812]


In [42]:
arr1=np.empty((3,3),dtype=int)
print(arr1)

[[                  0 4607182418800017408 4611686018427387904]
 [4607182418800017408 4611686018427387904 4613937818241073152]
 [4611686018427387904 4613937818241073152 4616189618054758400]]


In [43]:
arr=np.empty((2,3))
print(arr)

[[1.47793767 0.48980172 0.01715385]
 [1.06408195 2.12369148 0.80546175]]


In [45]:
arr=np.empty((2,2,3))
print(arr)

[[[1.23897438e-311 3.16202013e-322 0.00000000e+000]
  [0.00000000e+000 7.56587583e-307 7.78432588e-071]]

 [[1.40937316e-075 3.11050001e-032 5.22469853e-037]
  [1.39403711e+165 3.14252621e+179 1.16256872e+165]]]


In [2]:
import numpy as np
arr1=np.empty([2,3])
print(arr1)

[[-6.95250444e-310  1.11728592e-085  1.05054367e-311]
 [ 1.05054367e-311  3.95252517e-323  2.47032823e-323]]


# 13.logspace()

In [46]:
arr = np.logspace(0, 3, 4)
print(arr)

[   1.   10.  100. 1000.]


In [49]:
arr1 = np.logspace(0, 4, 5, base=2,dtype=int)
print(arr1)


[ 1  2  4  8 16]


In [50]:
arr2 = np.logspace(0, 1, 5)
print(arr2)


[ 1.          1.77827941  3.16227766  5.62341325 10.        ]


In [51]:
arr3 = np.logspace(1, 6, 6)
print(arr3)


[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06]


In [52]:
arr2d = np.logspace(0, 3, 6).reshape(2,3)
print(arr2d)
print("Shape:", arr2d.shape)


[[   1.            3.98107171   15.84893192]
 [  63.09573445  251.18864315 1000.        ]]
Shape: (2, 3)


# 14.rand()

In [4]:
arr=np.random.rand(10)
print(arr)

[0.24840807 0.30175304 0.1657965  0.03011841 0.59575651 0.85968285
 0.02811533 0.16831194 0.32937478 0.62480085]


In [8]:
arr=np.random.rand(2,3)
print(arr)

[[0.77760861 0.32243679 0.79268249]
 [0.53609073 0.40401129 0.53260358]]


In [12]:
arr=10+(50-10)*np.random.rand(3,3)
arr

array([[42.14383171, 12.22135472, 24.48750765],
       [38.15144043, 47.61677386, 18.03635277],
       [37.71185687, 11.72274008, 22.00755227]])

In [14]:
arr=0+(50-0)*np.random.rand(3,3)
arr
# x=a+(b−a)∗rand()

array([[ 9.47362362, 35.57816905, 46.78083742],
       [15.4272639 , 25.63402796,  2.15055689],
       [43.76791109, 19.79244699, 11.85882133]])

# Numpy Data Types and Type casting

In [28]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


dtype('int32')

In [25]:
arr=np.array([1,2.1,'3',4,5])
print(arr)
print(arr.dtype)

['1' '2.1' '3' '4' '5']
<U32


In [26]:
arr=np.array([1,2.1,3,4,5])
print(arr)
print(arr.dtype)

[1.  2.1 3.  4.  5. ]
float64


In [27]:
lst=[1,2,'abc',3.14]
arr=np.array(lst)
print(arr)

['1' '2' 'abc' '3.14']


In [33]:
arr=np.array([1,2.1,3,4],dtype=np.int64)
print(arr,arr.dtype)

[1 2 3 4] int64


In [38]:
arr=np.array([1,2.1,3,4],dtype=np.str_)
print(arr,arr.dtype)

['1' '2.1' '3' '4'] <U3


In [58]:
arr=np.array([1,2,3])
arr.dtype

dtype('int32')

In [59]:
arr=np.array([1,2,3],dtype='S')
arr

array([b'1', b'2', b'3'], dtype='|S1')

In [60]:
arr=np.array([1,2,3],dtype='f')
arr

array([1., 2., 3.], dtype=float32)

In [62]:
arr=np.array([1,2,3],dtype=bool)
arr

array([ True,  True,  True])

# astype()--> type Casting

In [66]:
arr=np.array([1,2,3])
arr.dtype

dtype('int32')

In [67]:
new_arr=arr.astype(np.float64)
print(new_arr,new_arr.dtype)

[1. 2. 3.] float64


In [68]:
new_arr2=arr.astype(np.str_) # or arr.astype(str)
print(new_arr2,new_arr2.dtype)

['1' '2' '3'] <U11


In [70]:
arr_f=new_arr2.astype(float)
arr_f

array([1., 2., 3.])

In [69]:
# Type casting Errors
arr=np.array(['1','2','abc'])
arr2=arr.astype(np.int64)

ValueError: invalid literal for int() with base 10: 'abc'

In [49]:
arr=np.array([1,2,3],[4,5,6]) # we can pass only one list to an array
arr

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [63]:
arr=np.array([[1,2,3],[4,5,6]]) # we can pass only one list to an array
print(arr)
print(arr.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [64]:
arr1=arr.astype(bool)
arr1

array([[ True,  True,  True],
       [ True,  True,  True]])

# size

In [71]:
arr=np.array([1,2,3])
arr.size

3

In [73]:
arr=np.array([[1,2,3],[4,5,6]]) 
print(arr.shape) #size=2*3=6
arr.size

(2, 3)


6

In [74]:
arr=np.zeros((2,3,4))
print(arr)
print(arr.size) #2*3*4=24

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
24


In [76]:
arr=np.array([])
print(arr.size)

0


In [77]:
arr=np.array([1])
print(arr)

[1]


# itemsize

In [79]:
arr=np.array([1,2,3],dtype='i8')
arr.itemsize

8

In [80]:
arr=np.array([1,2,3,4.1])
arr.itemsize

8

In [82]:
arr=np.array([1,2,3,4],dtype=str)
print(arr.dtype,arr.itemsize)

<U1 4


In [83]:
arr=np.array([1,2,3,4],dtype=complex)
print(arr.dtype,arr.itemsize)

complex128 16


# nbytes
##### nbytes=size*itemsize

In [3]:
import numpy as np
arr=np.array([1,2,3])
print(arr.size)
print(arr.itemsize)

3
4


In [4]:
print(arr.nbytes)

12


# reshape()
->changes the shape of an array

In [2]:
import numpy as np
arr=np.arange(12).reshape(3,-1)
arr
# -1 → NumPy will automatically calculate the number of columns so that the total number of elements stays the same.
# columns=totalelements/rows=12/3=4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
arr=np.arange(5).reshape(2,3)

ValueError: cannot reshape array of size 5 into shape (2,3)

In [4]:
arr=np.array([1,2,3,4])
np.reshape(arr,(2,2))


array([[1, 2],
       [3, 4]])

In [7]:
arr=np.array([1,2,3,4])
arr1=arr.reshape([2,2])
arr1

array([[1, 2],
       [3, 4]])

In [8]:
a = np.arange(8)
b = a.reshape((-1, -1))  # ❌ Error, only one -1 allowed


ValueError: can only specify one unknown dimension

# ravel()

In [10]:
arr=np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
ravel=arr.ravel()  #Syntax1
print(ravel)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
ravel=np.ravel(arr)  # Syntax2
print(ravel)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [14]:
ravel[0]=100
print(ravel) 
print(arr)
# whenever we make changes in ravel array it will reflect in orginal array

[100   1   2   3   4   5   6   7   8   9  10  11]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [15]:
a = np.array([[1,2],[3,4]])
b = np.ravel(a, order='F') #order='F' means flatten column-wise instead of row-wise.
print(b) 


[1 3 2 4]


In [16]:
a = np.arange(10)[::2]  
b = np.ravel(a)
print(b)  


[0 2 4 6 8]


In [19]:
a=np.arange(6).reshape(2,3)
b=a.ravel()
b

array([0, 1, 2, 3, 4, 5])

# flatten()

In [20]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=a.flatten() 
print(b)

[1 2 3 4 5 6 7 8]


In [23]:
b[0]=100
print(b)
print(a)
# doesnt make any changes in the orginal array

[100   2   3   4   5   6   7   8]
[[1 2 3 4]
 [5 6 7 8]]


In [25]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a.flatten(order='F')
print(b) 

[1 4 7 2 5 8 3 6 9]


In [26]:
a = np.arange(8).reshape(2,2,2)
print(a)
b = a.flatten()
print(b)  

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[0 1 2 3 4 5 6 7]


In [33]:
a = np.arange(6).reshape(2,3)
b = a[:,::2].ravel()
c = a[:,::2].flatten()
print(a)
print(b)
print(c)
b[0] = 100
c[0] = 200
print(a)  
# ravel() cannot always return a view if the array is non-contiguous.

[[0 1 2]
 [3 4 5]]
[0 2 3 5]
[0 2 3 5]
[[0 1 2]
 [3 4 5]]


In [36]:
a = np.arange(6)
b = a[::].ravel()
c = a[::].flatten()
b[0] = 100
c[0] = 200
print(a)  # ravel changes view if possible

[100   1   2   3   4   5]


# Arithmetic Operations on Array
#### If we have arrays of the same shape, operations are applied element by element.

In [38]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [39]:
# Addition
print(a+b)

[5 7 9]


In [41]:
# Subraction
print(a-b)

[-3 -3 -3]


In [44]:
#  Divison
print(b/a)

[4.  2.5 2. ]


In [46]:
# Integer Divison
print(b//a)

[4 2 2]


In [47]:
# multiplication
print(a*b)

[ 4 10 18]


In [48]:
# modulus--> remainder
print(b%a)

[0 1 0]


In [49]:
# Exponents-->power
print(a**b)

[  1  32 729]
