In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

In [6]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


# Dimensions(ndim)
#### Dimension = number of levels in the array (1D = line, 2D = table, 3D = cube).

In [16]:
a=np.array(5)
print(f'Dimensions: {a.ndim}')
print(a)
b=np.array([1,2,3]) 
print(f'Dimensions: {b.ndim}')
print(b)
c=np.array([[1,2,3],[4,5,6]])
print(f'Dimensions: {c.ndim}')
print(c)
d=np.array([[[1,2,3],[4,5,6]]])
print(f'Dimensions: {d.ndim}')
print(d)
e=np.array([[[[]]]])
print(f'Dimensions: {e.ndim}')
f=np.array([[[[[[],[]]]]]])
print(f'Dimensions: {f.ndim}')

Dimensions: 0
5
Dimensions: 1
[1 2 3]
Dimensions: 2
[[1 2 3]
 [4 5 6]]
Dimensions: 3
[[[1 2 3]
  [4 5 6]]]
Dimensions: 4
Dimensions: 6


In [31]:

a = np.array([
    [[1, 2, 3],
     [4, 5, 6],[7,8,9]],
    
    [[7, 8, 9],
     [10, 11, 12],[13,14,15]]
])

print(a.ndim)   

3


In [32]:
import numpy as np

a = np.array([[1, 2], [3]])


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

# ndmin

#### ndmin is an argument used in np.array() to set the minimum number of dimensions an array should have.

In [18]:
a=np.array([1,2,3],ndmin=5)
print(a)
print(a.ndim)

[[[[[1 2 3]]]]]
5


In [19]:
b=np.array([[[1,2,3],[4,5,6]]],ndmin=5)
print(b)
print(b.ndim)

[[[[[1 2 3]
    [4 5 6]]]]]
5


In [20]:
c=np.array([[1,2,3]],ndmin=1)
print(c)
# What happens if you set ndmin smaller than the data’s current dimension?
# ➡️ Answer: Nothing changes. NumPy ignores it since the data already has higher dimensions.

[[1 2 3]]


In [36]:
d=np.array(5,ndmin=6)
print(d)

[[[[[[5]]]]]]


# NumPy Array Indexing

In [39]:
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[-1])
print(arr[-3])
print(arr[3]+arr[2])

1
4
2
7


In [41]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0,-1])
print(arr[1,-1])
print(arr[1,0])
print(arr[0,0])

5
10
6
1


In [50]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,-1])
print(arr[1,1,1])
print(arr[0,0,2])
print(arr[1,0,1])

6
11
3
8


# Slicing

In [51]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[0:5:2])

[1 3 5]


In [53]:
arr=np.array([[1,2,3,4],[6,7,8,9]])
print(arr[1,1:])
print(arr[0,-4:-1:2])

[7 8 9]
[1 3]


In [57]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,2])
print(arr[0:2,0:])
print(arr[0:2,2:4])
print(arr[0:2,0::2])

[3 8]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[3 4]
 [8 9]]
[[ 1  3  5]
 [ 6  8 10]]


# DataTypes

# dtype
#### In NumPy, dtype stands for “data type”. It tells NumPy what kind of data is stored in an array

In [19]:
#integer 
arr_i=np.array([1,2,3,4,5],dtype='i')
print(arr_i)
print(arr_i.dtype)
arr_i64 = np.array([1, 2, 3, 4, 5], dtype='int64')
print(arr_i64.dtype)

# Boolean
arr_b = np.array([True, False, True], dtype='b')
print("Boolean (b):", arr_b)
print(arr_b.dtype) 

# Unsigned Integer
arr_u = np.array([1, 2, 3], dtype='u8')
print("Unsigned Integer (u):", arr_u)
print(arr_u.dtype)

# Float
arr_f = np.array([1.5, 2.5, 3.5], dtype='f')
print("Float (f):", arr_f)
print(arr_f.dtype)

# Complex Float
arr_c = np.array([1+2j, 3+4j], dtype='c8')
print("Complex Float (c):", arr_c)
print(arr_c.dtype)

# Timedelta
arr_m = np.array(['1', '2', '3'], dtype='m')  # timedelta64
print("Timedelta (m):", arr_m)
print(arr_m.dtype)

# Datetime
arr_M = np.array(['2025-10-08', '2025-10-09'], dtype='M')  # datetime64
print("Datetime (M):", arr_M)
print(arr_M.dtype)

# Object
arr_O = np.array([{'a':1}, [1,2,3], "hello"], dtype='O')
print("Object (O):", arr_O)
print(arr_O.dtype)

# Byte String
arr_S = np.array([b'abc', b'def'], dtype='S')
print("Byte String (S):", arr_S)
print(arr_S.dtype)

# Unicode String
arr_U = np.array(['abc', 'def'], dtype='U')
print("Unicode String (U):", arr_U)
print(arr_U.dtype)

# Void (raw memory / fixed-size block)
arr_V = np.zeros(3, dtype='V10')  # 3 blocks of 10 bytes each
print("Void (V):", arr_V)
print(arr_V.dtype)

[1 2 3 4 5]
int32
int64
Boolean (b): [1 0 1]
int8
Unsigned Integer (u): [1 2 3]
uint64
Float (f): [1.5 2.5 3.5]
float32
Complex Float (c): [1.+2.j 3.+4.j]
complex64
Timedelta (m): [1 2 3]
timedelta64
Datetime (M): ['2025-10-08' '2025-10-09']
datetime64[D]
Object (O): [{'a': 1} list([1, 2, 3]) 'hello']
object
Byte String (S): [b'abc' b'def']
|S3
Unicode String (U): ['abc' 'def']
<U3
Void (V): [b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00']
|V10
